---
title: "Results Analysis"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("main.R")
library(ggplot2)
```

First we will load the variables.
```{r}
vars_1dim <- c( 'alpha', 'beta_home', 'beta_away', 'sigma_deficit', 'beta_intercept')
walk(
  vars_1dim,
  ~  cat(., ' = ', res[[.]], '\n')
)
```

We can see the most important statistics in order:
```{r}
res$beta_a[order(res$beta_a, decreasing=T)]
res$beta_a[order(abs(res$beta_a), decreasing=T)]
res$beta_b[order(res$beta_b, decreasing=T)]
res$beta_b[order(abs(res$beta_b), decreasing=T)]
```

Let us see who the best players are (with at least 100 games in the data).
```{r}
player_mean_data$score_a <- res$player_value_raw_a
player_mean_data$score_b <- res$player_value_raw_b
std_score_a <- scale(player_mean_data$score_a)
std_score_b <- scale(player_mean_data$score_b)
player_mean_data$score <- mean(c(res$beta_home[1], res$beta_away[1]))*std_score_a + mean(c(res$beta_home[2], res$beta_away[2]))*std_score_b
players <- topn_players_stan(res, df, players, n=100) %>%
  merge(player_mean_data[,c('playerId', 'score_a', 'score_b', 'score')])
scorecols <-  c('score', 'score_a', 'score_b')
walk(
  scorecols,
  function(sc) {
    cat('\n ', rep('=', 30), '\n score: ', sc, '\n')
    players %>%
      arrange(desc(.data[[sc]])) %>%
      head(20) %>%
      select(all_of(c('displayName', 'position', sc))) %>%
      print
  }
)
```

We can also show the top 5 players by position:
```{r}
walk(
  scorecols,
  function(scorecol) {
    cat('\n ', rep('=', 30), '\n score: ', scorecol, '\n')
    players %>%
      group_by(position) %>%
      slice_max(order_by=.data[[scorecol]], n=5) %>%
      group_walk(~ {
        cat(paste0('\n', 'score: ', scorecol, ', position: ', .y, '\n'))
        print(.x[, c('displayName', scorecol)])
        cat('\n')
      })
  }
)
```

We can now try and apply this to the games in our dataset.
```{r}
walk2(
  c('deficits', 'deficits_expc'),
  c("Residual Density Plot (Expected ELO)","Residual Density Plot (Observed ELO)"),
  ~ {
    (ggplot(data.frame(Residual=stan_input$deficit-pred[[.x]]), aes(x=Residual)) +
      geom_histogram(aes(y=stat(density)), colour=1, fill="white", bins=10) +
      geom_density() +
      ggtitle(.y)) %>%
      print
  }
)
```

We can now try and apply this to compute win prediction accuracy.
```{r}
game_wins <- as.numeric(stan_input$deficit>0)
print( sum(game_wins==pred$wins)/length(game_wins) )
```

We can show the scores by origin:
```{r}
walk(
  scorecols,
  function(sc) {
    cat('\n score: ', sc, '\n')
    players %>%
      group_by(origin) %>%
      summarise (avg_score = mean(.data[[sc]]), n_players=n()) %>%
      arrange(desc(avg_score)) %>%
      dplyr::filter(n_players >= 5) %>%
      head(10) %>%
      print
  }
)
```
